### ISSUE TITLE
/api/token/validate requires AllowAnonymous attribute

### ISSUE THREAD

**Issue by bcbeatty** [ddiyteam/webapitemplate_netcore#3]
I may be missing something,
But I tried calling /api/token/generate
then taking that value to POST /api/token/validate
and I always get a 401.
Once I add [AllowAnonymous ] to ValidateToken, then I'll get a 200 and a result of 
```
{
    "isValid": true
}
```

I've tried adding the token in the header as a Bearer token but it still fails to authenticate.
Ideas?

**Comment by ddiyteam** [comment]
To authorize with generated token you need to send it with headers when calling a method.

1. You may insert token in swagger's authorize parameters: Authorize button -> Value input. Swagger will place token to headers.
Format:
`bearer {your_token}`

2. You may add token to headers when you make a http api calls from external app.
Format:
`authorization: bearer {your_token}`

Adding AllowAnonymous to ValidateToken disables authorization for method. 
The ideas was to make token validation only when you was authorized, that's why ValidateToken method does not have AllowAnonymous attribute and need authorization like others methods.
But if you don't need this function (validate token) you may delete this method in api. 

Thank you.
